### PR TITLE
feat(dialog): converted floating action button to a normal button

### LINKED ISSUE #60: Remove floating action button from clause template modal
#### Description

As discussed with @Michael-Grover, the floating action button is rarely seen in desktop apps. Therefore this should be changed to a normal button.

OS info:-
Mac OS Catalina(v10.15.2)

### PR DESCRIPTION
**Pull request by nik72619c**
Fixes #60 
Signed-off-by: nik72619c <nikhilsharmarockstar21@gmail.com>

Screenshot 2020-03-20 at 11 45 13 PM
@DianaLease @dselman Let me know if this needs any changes.

### CODE REVIEW

**Review by DianaLease — APPROVED** [review]
Looks great! Requesting a review from @Michael-Grover to also take a look.

**Comment by DianaLease** [comment]
hi @nik72619c ! Can you please resolve the merge conflicts for this one? Thanks!

**Comment by DianaLease** [comment]
> hi @nik72619c ! Can you please resolve the merge conflicts for this one? Thanks!

^ following up here too :)

**Comment by nik72619c** [comment]
@DianaLease resolved merge conflicts

**Comment by DianaLease** [comment]
> @DianaLease resolved merge conflicts

I think something strange happened here because now in the diff I see 8 files changed when I believe the changes should only effect `src/NewSmartClauseDialog.js`

**Comment by nik72619c** [comment]
@DianaLease should I file another PR for this maybe ?

**Comment by DianaLease** [comment]
> @DianaLease should I file another PR for this maybe ?

sure, thanks!

**Pull request closed without merging**
