### PR TITLE
feat(header): add cicero logo in the banner

### LINKED ISSUE #72: Add cicero logo in the app banner
#### Description
Based on the discussion with @Michael-Grover, the logo for cicero needs to be added on the banner of the add-in project.

image (1)

### PR DESCRIPTION
**Pull request by nik72619c**
Fixes #72 
Screenshot 2020-03-21 at 4 18 19 AM

Signed-off-by: nik72619c <nikhilsharmarockstar21@gmail.com>

### CODE REVIEW

**Review by DianaLease — APPROVED** [review]
LGTM. @Michael-Grover ?

**Review by Michael-Grover — APPROVED** [review]
lgtm

**Comment by DianaLease** [comment]
@nik72619c Can you resolve the merge conflicts please?

**Comment by nik72619c** [comment]
@DianaLease working on it.

**Review by dselman — APPROVED** [review]

**Comment by DianaLease** [comment]
@nik72619c can you please make sure each commit has the DCO signoff?

**Comment by nik72619c** [comment]
@DianaLease should I squash my commits into one and amend the signoff to the last commit ?

**Comment by jeromesimeon** [comment]
> @DianaLease should I squash my commits into one and amend the signoff to the last commit ?

It might be a good opportunity to clean up this commit log. All I see are "Merge" commits.

**Comment by nik72619c** [comment]
@jeromesimeon facing some issue with rebasing. I think I should file another fresh PR and close this one.

**Pull request closed without merging**
