### PR TITLE
feat(*): added autoopen taskpane feature

### LINKED ISSUE #133: Taskpane should open Automatically when document is opened.
#### Is your feature related to a problem? Please describe.
When a user opens a document and has add-in already installed. Then, the add-in's `taskpane` should open when document is  opened.

#### Describe the solution you would like
It should be left on the user whether he wants to enable this `autoopen taskpane `feature when using word. Maybe, we can have a button that enables and disables this feature.

#### Additional Context
I am working on this.

### PR DESCRIPTION
**Pull request by arteevraina**
## Screenshot
image

Please Review and suggest changes @DianaLease @dselman  @Michael-Grover :) 
Signed-off-by: Arteev Raina <arteevraina@gmail.com>

### CODE REVIEW

**Review by DianaLease — COMMENTED** [review]
Cool! However, when I  re-open the document after setting auto-open to on, the task pane is opened but the add-in doesn't load. Is that how it behaves for others?

**Comment by Michael-Grover** [comment]
One adjustment I would suggest is to make this a checkbox that says “Open Cicero Word add-in on launch” next to it instead of two buttons.

I'm not sure if auto open needs an entire tab with the same prominence as "clause template" and "templates". Where do other word add-ins put their auto-open setting? Is this usually a prominent part of the word add-in UI? I would think the auto-open setting is something a user would choose once and then never think about again, so I don't think it should be so prominent in the UI.

**Comment by a4aditya** [comment]
@Michael-Grover why not to put this option inside a side drawer? What do you think?

**Comment by arteevraina** [comment]
> Cool! However, when I re-open the document after setting auto-open to on, the task pane is opened but the add-in doesn't load. Is that how it behaves for others?
ezgif com-crop

@DianaLease This is how it behaves for me in word online.

**Comment by arteevraina** [comment]
@a4aditya Which side drawer you are referring to?

**Comment by a4aditya** [comment]
I have been working on the side drawer for the add-in. I think this will be useful for the user.
what do you guys think @Michael-Grover @arteevraina @DianaLease ? Should I create a Issue for the same and then add this feature if you guys think its needed.  

demo

**Comment by Michael-Grover** [comment]
I don't think a side drawer is necessary yet as we only have one setting.

For now let's put it here and if there are more settings in the future, we can consider a dedicated page or side drawer for them.
image

**Comment by arteevraina** [comment]
Thanks @Michael-Grover I will fix that up :)

**Comment by Michael-Grover** [comment]
@a4aditya I didn't see your last comment with the side drawer demo. That looks interesting. Once we have more ideas for settings we should consider that and other options for showing the settings.

I haven't looked at many Microsoft Word Add-ins yet but I will be doing that today so I can see what UI patterns are common in Word Add-ins and give better recommendations.

**Comment by a4aditya** [comment]
Thanks @Michael-Grover .(Just for reference, I have seen multiple add-ins and found side drawer as a common feature, see if that works out :+1: ).

**Comment by Michael-Grover** [comment]
@arteevraina you mentioned in Slack that this is difficult to do as a simple checkbox. In that case, I think we should consider shelving this feature for now. @irmerk and I discussed this and agree this is pretty low priority.

**Comment by arteevraina** [comment]
Closing this PR and sending a fresh PR for this.

**Pull request closed without merging**
