### PR TITLE
fix(Footer):changed color  on hover and text-color

### LINKED ISSUE #107: organisation Link Color in on hover matching with backgroung color
image

I would like to work on this.

### PR DESCRIPTION
**Pull request by arteevraina**
Fixes: #107 
**Without Hover**
image

**With Hover**
image

Please Review @Michael-Grover @dselman @DianaLease :)

### CODE REVIEW

**Comment by Michael-Grover** [comment]
Thanks @arteevraina , here's my feedback

- make background color a light gray like this:
image
- make main text black
- make hyperlink text blue, with an underline appearing upon hover
- make drop shadow more subtle or remove entirely
- left align text
- make the text not italicized

**Comment by arteevraina** [comment]
Hi @Michael-Grover , Thanks for your valuable feedback. I have made the changes as per your feedback. Please Review and Suggest changes :)

**Without Hover**
image
**With Hover**
image

**Comment by Michael-Grover** [comment]
thanks for making the changes

Can we make the hyperlink use the same blue in the default and hovered states so that it doesn't change color? Let's use this blue: 
image

What are the orange lines on the side of the images?

**Comment by arteevraina** [comment]
Sure, I will make the changes. Those orange lines are the scroll bars in` word-online's` taskpane. They are not in the UI of this project.

**Comment by arteevraina** [comment]
@Michael-Grover Changes have been made :)
image

**Review by Michael-Grover — APPROVED** [review]
thanks looks good

**Review by DianaLease — APPROVED** [review]

**Pull request merged**
